// SPDX-License-Identifier: MPL-2.0

#pragma once

#include <string_view>

namespace aether::dab_transform_gpu {

// Shared analytical inverse for the segmented bilinear patches generated by
// TileBrush::DabTransform. Ordinary paint and Wet must use the same mapping or
// their connected/refined ribbons disagree at turns.
inline constexpr std::string_view kMappingGlsl = R"glsl(
float cross2d(vec2 a, vec2 b) { return a.x*b.y - a.y*b.x; }
bool tryStretchST(vec2 E, vec2 F, vec2 G, vec2 h, float t, out vec2 st) {
    const float margin = 0.002;
    if (t < -margin || t > 1.0 + margin) return false;
    vec2 denom = E + G * t;
    float s;
    if (abs(denom.x) > abs(denom.y)) {
        if (abs(denom.x) < 1e-8) return false;
        s = (h.x - F.x * t) / denom.x;
    } else {
        if (abs(denom.y) < 1e-8) return false;
        s = (h.y - F.y * t) / denom.y;
    }
    if (s < -margin || s > 1.0 + margin) return false;
    st = clamp(vec2(s, t), vec2(0.0), vec2(1.0));
    return true;
}
bool inverseStretchQuad(vec2 P, vec2 q0, vec2 q1, vec2 q2, vec2 q3, out vec2 st) {
    vec2 E0 = q1 - q0;
    vec2 F0 = q3 - q0;
    float quadScale = max(max(length(E0), length(F0)),
                          max(length(q2 - q1), length(q2 - q3)));
    float invScale = 1.0 / max(quadScale, 1e-6);
    vec2 E = E0 * invScale;
    vec2 F = F0 * invScale;
    vec2 G = (q0 - q1 + q2 - q3) * invScale;
    vec2 h = (P - q0) * invScale;
    float k2 = cross2d(G, F);
    float k1 = cross2d(E, F) + cross2d(h, G);
    float k0 = cross2d(h, E);
    if (abs(k2) < 1e-8) {
        if (abs(k1) < 1e-8) return false;
        return tryStretchST(E, F, G, h, -k0 / k1, st);
    }
    float disc = k1*k1 - 4.0*k0*k2;
    if (disc < 0.0) return false;
    float root = sqrt(disc);
    float qStable = -0.5 * (k1 + ((k1 >= 0.0) ? root : -root));
    if (tryStretchST(E, F, G, h, qStable / k2, st)) return true;
    return abs(qStable) > 1e-8
        && tryStretchST(E, F, G, h, k0 / qStable, st);
}
vec2 cubicRail(vec2 start, vec2 startControl, vec2 endControl, vec2 end, float t) {
    float u = 1.0 - t;
    return start * (u*u*u) + startControl * (3.0*u*u*t)
         + endControl * (3.0*u*t*t) + end * (t*t*t);
}
)glsl";

} // namespace aether::dab_transform_gpu
