# SPDX-License-Identifier: MPL-2.0

# Generates the GLSL constant block for the 16-bin spectral pigment model
# (W = sRGB-linear -> reflectance, A = reflectance -> sRGB-linear), packed as
# mat4 (16-float containers accessed per-column as vec4). Emits to stdout.
import numpy as np

NB = 16
lam = np.linspace(380.0, 730.0, NB)

def gauss(x, mu, s1, s2):
    t = (x - mu) * np.where(x < mu, s1, s2)
    return np.exp(-0.5 * t * t)

xb = (1.056*gauss(lam,599.8,0.0264,0.0323)+0.362*gauss(lam,442.0,0.0624,0.0374)
      -0.065*gauss(lam,501.1,0.0490,0.0382))
yb = (0.821*gauss(lam,568.8,0.0213,0.0247)+0.286*gauss(lam,530.9,0.0613,0.0322))
zb = (1.217*gauss(lam,437.0,0.0845,0.0278)+0.681*gauss(lam,459.0,0.0385,0.0725))

d65_10 = np.array([49.98,54.65,82.75,91.49,93.43,86.68,104.87,117.01,117.81,114.86,
    115.92,108.81,109.35,107.80,104.79,107.69,104.41,104.05,100.00,96.33,95.79,
    88.69,90.01,89.60,87.70,83.29,83.70,80.03,80.21,82.28,78.28,69.72,71.61,74.35,
    61.60,69.89])
d65 = np.interp(lam, np.arange(380.0,731.0,10.0), d65_10)

M = np.array([[3.2406255,-1.5372080,-0.4986286],
              [-0.9689307,1.8757561,0.0415175],
              [0.0557101,-0.2040211,1.0569959]])
k = 1.0/(yb*d65).sum()
T = k*np.vstack([xb*d65, yb*d65, zb*d65])
A = M @ T                                     # 3 x 16
D2 = np.eye(NB)[:-2]-2*np.eye(NB)[1:-1]+np.eye(NB)[2:]
H = D2.T@D2 + 1e-8*np.eye(NB)
Hi = np.linalg.inv(H)
W = Hi@A.T@np.linalg.inv(A@Hi@A.T)            # 16 x 3

def mat4(vec16, name):
    v = ", ".join(f"{x:.8f}" for x in vec16)
    return f"const mat4 {name} = mat4({v});"

print("// --- generated by scripts/pigment_gen_glsl.py (16-bin spectral model) ---")
print(f"const float PG_EPS = 1e-4;")
print(mat4(W[:,0], "PG_WR"))     # reflectance += lin.r * PG_WR
print(mat4(W[:,1], "PG_WG"))
print(mat4(W[:,2], "PG_WB"))
print(mat4(A[0,:], "PG_AR"))     # lin.r = dot(PG_AR, rho)
print(mat4(A[1,:], "PG_AG"))
print(mat4(A[2,:], "PG_AB"))
